[phases.setup]
nixPkgs = ["nodejs_18", "python311", "python311Packages.pip", "pnpm-9_x"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "gunicorn -w 4 -b 0.0.0.0:$PORT api.index:app"
