[phases.setup]
nixPkgs = ["nodejs_18", "python311", "python311Packages.pip", "python311Packages.virtualenv", "pnpm-9_x"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn -w 4 -b 0.0.0.0:$PORT api.index:app"
